set -g mouse on
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down
bind -T root WheelUpPane if-shell -F "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -X scroll-up"
bind -T root WheelDownPane if-shell -F "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -X scroll-down"
set -g default-terminal "tmux-256color"
setw -g mode-keys vi
